#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
SDK=`$SCRIPT_DIR/get-sdk-install-folder`

ssh \
  mersdk@127.0.0.1 \
  -p 2222 \
  -i "$SDK/vmshare/ssh/private_keys/engine/mersdk" \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  "$@"
