#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
SDK=`$SCRIPT_DIR/get-sdk-install-folder`

REMOTE_WD="${PWD/#$HOME//home/mersdk/share}"

"$SCRIPT_DIR/build-env-ssh" -q "cd \"$REMOTE_WD\" && sb2"
