/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i dbus/interface_types.h -N -p manager_interface.h: ../../SailfishConnect/app/src/dbus/ofono/org.ofono.Manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MANAGER_INTERFACE_H
#define MANAGER_INTERFACE_H

#include <tuple>

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

namespace SailfishConnect {
namespace Ofono {

typedef std::tuple<QDBusObjectPath, QVariantMap> ObjectProperties;
typedef QList<ObjectProperties> ObjectPropertiesArray;


/*
 * Proxy class for interface org.ofono.VoiceCall
 */
class VoiceCall : public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.VoiceCall"; }

public:
    VoiceCall(const QString path, QObject *parent = 0);

    QDBusPendingReply<QVariantMap> GetProperties();

Q_SIGNALS:
    void DisconnectReason(const QString& reason);
    void PropertyChanged(const QString& property, const QVariant& value);
};


/*
 * Proxy class for interface org.ofono.VoiceCallManager
 */
class VoiceCallManager : public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.VoiceCallManager"; }

public:
    VoiceCallManager(const QString path, QObject *parent = 0);

    QDBusPendingReply<ObjectPropertiesArray> GetCalls();

Q_SIGNALS:
    void CallAdded(const QDBusObjectPath &path, const QVariantMap &properties);
    void CallRemoved(const QDBusObjectPath &path);
};


/*
 * Proxy class for interface org.ofono.Manager
 */
class Manager : public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.Manager"; }

public:
    Manager(QObject *parent = 0);

    QDBusPendingReply<ObjectPropertiesArray> GetModems();

Q_SIGNALS:
    void ModemAdded(const QDBusObjectPath &path, const QVariantMap &properties);
    void ModemRemoved(const QDBusObjectPath &path);
};


void registerTypes();

} // namespace Ofono
} // namespace SailfishConnect

Q_DECLARE_METATYPE(SailfishConnect::Ofono::ObjectProperties);
Q_DECLARE_METATYPE(SailfishConnect::Ofono::ObjectPropertiesArray);

#endif
