#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
cd "${SCRIPT_DIR}/.."

TRANSLATIONS=`find po/ -maxdepth 1 ! -name templates | cut -d/ -f2 | xargs echo`
SAILFISHCONNECT_DOMAINS="sailfishconnect-app sailfishconnect-plugins"

EXTOPTS="--c++ --kde --sort-output \
    --from-code=UTF-8 \
    -c i18n \
    -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 \
    -kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
    -kI18N_NOOP:1 -kI18NC_NOOP:1c,2"
EXTOPTS="--c++ --kde --sort-output \
    --from-code=UTF-8 \
    -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 \
    -kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
    -kI18N_NOOP:1 -kI18NC_NOOP:1c,2"
XGETTEXT="xgettext $EXTOPTS"
potdir=po/templates
podir=po

echo "-- Create templates"
mkdir -p $potdir
find plugins/ pluginscommon/ -name '*.cpp' | xargs $XGETTEXT -o $potdir/sailfishconnect-plugins.pot
find app/ -name '*.cpp' -o -name '*.qml' | xargs $XGETTEXT -o $potdir/sailfishconnect-app.pot

echo "-- Merge translations"
for translation in $TRANSLATIONS
do
    for domain in $SAILFISHCONNECT_DOMAINS
    do
        dest="$podir/$translation/$domain.po"
        if [ -f "$dest" ]
        then
            echo "Merge $translation for $domain"
            mkdir -p "$podir/$translation"
            msgmerge --sort-output -q --lang=$translation -o "$dest.new" "$dest" "$potdir/$domain.pot"
            mv "$dest.new" "$dest"
        else
            echo "Create $translation for $domain"
            cp "$potdir/$domain.pot" "$dest"
        fi
    done
done