#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
cd "${SCRIPT_DIR}/.."

SDK=`dev/get-sdk-install-folder`
REMOTE_ROOT="${PWD/#$HOME//home/mersdk/share}"

# dev/build-shell << EOF
#   set -e
#   cd "$REMOTE_ROOT"
#   mb2 -X -t \$(sdk-assistant target list | grep armv7 | sort -r | head -1) make qm 
# EOF

tx push --translations --language es --source
tx pull --all --force