#!/bin/bash -e

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`
cd "${SCRIPT_DIR}/.."

TRANSLATIONS=`find po/ -maxdepth 1 ! -name templates | cut -d/ -f2 | xargs echo`
KDECONNECT_DOMAINS="kdeconnect-core kdeconnect-plugins"

potdir=po/templates
podir=po

for translation in $TRANSLATIONS
do
    for domain in $KDECONNECT_DOMAINS
    do
        mkdir -p "$podir/$translation"
        echo "Copy $translation for $domain"
        cp "kdeconnect-kde/po/$translation/$domain.po" "$podir/$translation/$domain.po"
    done
done