name: SailfishConnect build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  SFOS_RELEASE: 4.5.0.18

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check style
        run: python3 scripts/bad-style.py bad-style.xml

  build:
    strategy:
      matrix:
        arch: ['armv7hl', 'i486', 'aarch64']

    runs-on: ubuntu-latest
    needs: [check]

    env:
      SFOS_ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: .venv-conan-*
          key: venv-cache4-${{ matrix.arch }}

      - uses: actions/cache@v4
        with:
          path: .conan/data
          key: conan-cache2-${{ env.SFOS_RELEASE }}-${{ matrix.arch }}

      - name: Build ${{ matrix.arch }} RPMS
        uses: R1tschY/sailfish-build-rpm@v1
        with:
          arch: '${{ matrix.arch }}'
          release: '${{ env.SFOS_RELEASE }}'
          fix-version: false
          enable-debug: true

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: sailfishconnect-${{ matrix.arch }}
          path: RPMS
          compression-level: 0
