name: SailfishConnect build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

env:
  SFOS_RELEASE: 5.0.0.62

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Check style
        run: python3 scripts/bad-style.py bad-style.xml

  build:
    strategy:
      matrix:
        arch: ['armv7hl', 'i486', 'aarch64']

    runs-on: ubuntu-latest
    needs: [check]

    env:
      SFOS_ARCH: ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: .cpm-cache
          key: cpm-v1-${{ env.SFOS_RELEASE }}-${{ matrix.arch }}

      - name: Build ${{ matrix.arch }} RPMS
        uses: R1tschY/sailfish-build-rpm@v1
        with:
          arch: '${{ matrix.arch }}'
          release: '${{ env.SFOS_RELEASE }}'
          fix-version: false
          enable-debug: true

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: sailfishconnect-${{ matrix.arch }}
          path: RPMS
          compression-level: 0

  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    needs: [build]
    
    steps:
      - name: 'Get version'
        id: version
        run: |
          REF="${{ github.ref }}"
          version=${REF#refs/tags/v}
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Version: $version"
        shell: bash

      - name: Download RPMs
        uses: actions/download-artifact@v8
        with:
          path: RPMS
          pattern: harbour-sailfishconnect-*
          merge-multiple: true

      - name: Find RPMs
        id: rpms
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          find RPMS -name '*.rpm' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.version }}
          files: ${{ steps.rpms.outputs.files }}

      - name: Upload to openrepos.net
        uses: R1tschY/upload-to-openrepos@v1
        with:
          login: ${{ vars.OPENREPOS_LOGIN }}
          password: ${{ secrets.OPENREPOS_PASSWORD }}
          app-name: 'sailfish-connect'
          rpms: ${{ steps.rpms.outputs.files }}