name: SailfishConnect build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  RELEASE: 4.4.0.58

jobs:
  build-armv7hl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: .venv-conan-*
        key: venv-cache4-armv7hl

    - uses: actions/cache@v2
      with:
        path: .conan/data
        key: conan-cache2-4.0.1-armv7hl

    - name: Check style
      run: python3 scripts/bad-style.py bad-style.xml

    - name: Build armv7hl RPMS
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: 'armv7hl'
        release: '4.0.1.48'
        fix-version: false
        enable-debug: true

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: sailfishconnect-armv7hl
        path: RPMS

  build-i486:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: .venv-conan-*
        key: venv-cache4-i486

    - uses: actions/cache@v2
      with:
        path: .conan/data
        key: conan-cache2-4.0.1-i486

    - name: Build i486 RPMS
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: 'i486'
        release: '4.0.1.48'
        fix-version: false
        enable-debug: true

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: sailfishconnect-i486
        path: RPMS

  build-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: .venv-conan-*
        key: venv-cache4-aarch64

    - uses: actions/cache@v2
      with:
        path: .conan/data
        key: conan-cache2-4.0.1-aarch64

    - name: Build aarch64 RPMS
      uses: R1tschY/sailfish-build-rpm@v1
      with:
        arch: 'aarch64'
        release: '4.0.1.48'
        fix-version: false
        enable-debug: true

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: sailfishconnect-aarch64
        path: RPMS